version: '3'

services:
  # Сервіс для MySQL бази даних
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vaadin
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Сервіс для Spring Boot Vaadin додатку
  springbootapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot_kotlin_vaadin_app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/vaadin
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: true

volumes:
  mysql_data:
    driver: local