spring:
  flyway:
    baseline-on-migrate: true
  datasource:
    username: doadmin
    password: AVNS_YLRSs3s35Z1pGL1HWIC
    url: jdbc:mysql://db-mysql-lon1-21527-do-user-15948779-0.c.db.ondigitalocean.com:25060/defaultdb

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect